language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - USE_VALGRIND=1
  - USE_ASAN=1

matrix:
  exclude:
    - compiler: gcc
      env: USE_ASAN=1
    - os: osx
      env: USE_VALGRIND=1
  include:
    - os: osx
      compiler: gcc
      env: ""

addons:
  apt:
    packages:
      - valgrind

before_script:
  - if [[ "$USE_VALGRIND" ]]; then export MEMCHECK="valgrind -q --leak-check=full --error-exitcode=1"; fi
  - if [[ "$USE_ASAN" ]]; then export CFLAGS="-fsanitize=address -fno-omit-frame-pointer"; fi

script: make && make check
